apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: vsftpd
  ports:
    - name: port20
      protocol: TCP
      port: 20
      targetPort: 20
    - name: active
      protocol: TCP
      port: 21
      targetPort: 21
    - name: passive
      protocol: TCP
      port: 21000
      targetPort: 21000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-depl
  labels:
    app: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
                - containerPort: 20
                - containerPort: 21
                - containerPort: 21000
